name = "modpack"
author = "HexoKnight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
datapack-folder = "world/datapacks"
no-internal-hashes = true
